import { mcq } from './helpers.js';

export const theory = [
  mcq(
    'ast-t01',
    'HAM vs CMDB ownership',
    'Finance says the laptop is assigned to Alice; ITSM incidents still show Bob on the CI. Interview diagnosis?',
    [
      'Assets and CIs cannot represent the same device',
      'Split-brain: HAM assigned_to vs cmdb_ci.assigned_to not syncing (BR direction, import, or model). Pick a source of truth and sync one way',
      'assigned_to on CI is always copied from caller_id of the latest incident',
      'You must delete the CI so the asset wins',
    ],
    1,
    'HAM (alm_asset) is financial/lifecycle. CMDB is operational. OOTB field service may create/sync CI. Custom imports often update one table. Tickets use cmdb_ci.',
    'hard',
  ),
  mcq(
    'ast-t02',
    'install_status vs operational_status vs stockroom',
    'Asset In stock (6) still has a stockroom empty and CI Operational. What’s wrong with process, not just fields?',
    [
      'In stock does not require stockroom in any design',
      'In stock should be in a stockroom and usually not “in use” operationally; CI operational_status should be aligned or you will assign incidents to shelf hardware',
      'operational_status is only for knowledge articles',
      'Status 6 means Retired in all tables',
    ],
    1,
    'Choice values differ by table. Don’t memorize 6 without the label. Design: stock + not assigned_to + CI not operational.',
    'hard',
  ),
  mcq(
    'ast-t03',
    'updateMultiple retire by model',
    'Fix script: alm_asset addQuery model, set install_status 7, updateMultiple. Audit later shows serials vanished from reports of in-use assets but HAM contracts still bill. Issue?',
    [
      'updateMultiple cannot set install_status',
      'You skipped substatus/disposal date/CI sync/contract assets; bulk engine skip may also skip HAM life-cycle flows that notify finance',
      'Models cannot be queried',
      'Retired assets are deleted by OOTB nightly',
    ],
    1,
    'HAM has more than install_status. Asset tasks, depreciation, contract_rel. setWorkflow(false) makes it worse. Interview: data fix vs process.',
    'hard',
  ),
  mcq(
    'ast-t04',
    'Duplicate serial_number',
    'GlideAggregate COUNT > 1 on serial_number. Two hardware assets, one CI. What next, not just “merge”?',
    [
      'deleteMultiple the CI',
      'Determine which asset is the financial record, retire/duplicate-handle the other, and run IRE/identification on the CI serial so discovery doesn’t keep splitting',
      'Serial duplicates are allowed if names differ, so ignore',
      'Put both sys_ids in incident.cmdb_ci',
    ],
    1,
    'Duplicates are often one stolen/replaced device plus a bad import. IRE hardware rule uses serial — two assets fighting one identity.',
    'hard',
  ),
  mcq(
    'ast-t05',
    'Consumables vs hardware',
    'Ordering mice from catalog creates alm_hardware with unique serials empty. Better class?',
    [
      'Always hardware for anything physical',
      'Consumable/alm_consumable (quantity) vs hardware (serialized). Wrong class breaks inventory counts and assignment',
      'Mice must be cmdb_ci_linux_server',
      'Catalog cannot create assets',
    ],
    1,
    'HAM models: hardware, consumable, software entitlement (SAM). Interview if they say “everything is alm_hardware.”',
    'hard',
  ),
  mcq(
    'ast-t06',
    'Reference qualifier stockroom',
    'Users pick a stockroom from another building when install_status=In stock. Control?',
    [
      'Email them',
      'Mandatory stockroom Data Policy when in stock + qualifier on stockroom (location/building) + server BR; client-only is bypassed by mobile/import',
      'Hide stockroom forever',
      'Stockroom is a journal',
    ],
    1,
    'Same UI vs server lesson as incident mandatory fields.',
    'hard',
  ),
  mcq(
    'ast-t07',
    'Warranty encoded query',
    'warranty_expiration<javascript:gs.now() in a scheduled job. DST/timezone complaint from AU vs US?',
    [
      'javascript: in encoded query is illegal',
      'gs.now()/nowDateTime() vs date-only fields and instance TZ vs user TZ; compare using GlideDateTime at start-of-day in a defined TZ or date field operators',
      'Warranty dates cannot be queried',
      'Only GlideAggregate can read warranty_expiration',
    ],
    1,
    'glide_date vs glide_date_time. Community threads on “expired yesterday in US, still valid in AU.”',
    'hard',
  ),
  mcq(
    'ast-t08',
    'Asset task vs incident',
    'Broken laptop: incident vs asset task vs change. How do you decide in ITSM+HAM?',
    [
      'Always incident only',
      'Incident restores the user’s service; asset/repair task tracks the device lifecycle; a change if the fix is a controlled modification to a shared CI',
      'Always change_request',
      'Never incident if an asset exists',
    ],
    1,
    'Three tickets can be correct. Link them (CI/asset refs). Don’t force one table.',
    'hard',
  ),
  mcq(
    'ast-t09',
    'coalesce on import',
    'Transform map coalesce on asset_tag. Excel has blank tags. Result?',
    [
      'Rows with blank coalesce keys often collapse into one target or insert unpredictably — filter/ignore in onBefore when tag is empty',
      'Blank coalesce always creates perfect unique rows',
      'Coalesce ignores empty by deleting the row from Excel',
      'You cannot coalesce on asset_tag',
    ],
    0,
    'Community import interview: empty coalesce key is a foot-gun. Combine with coalesce case-sensitive option if tags differ by case.',
    'hard',
  ),
  mcq(
    'ast-t10',
    'GlideRecordSecure HAM',
    'Contractor with sn_eam roles sees costs. How?',
    [
      'cost has no ACLs possible',
      'Field-level ACL / data policy / encryption; also list vs form. Scripted reports using GlideRecord as admin bypass UI field ACLs',
      'Hide the field with CSS only',
      'Cost is always in g_scratchpad',
    ],
    1,
    'Financial fields need field ACLs. Widgets that query as a privileged user leak cost.',
    'hard',
  ),
  mcq(
    'ast-t11',
    'CI class vs asset model category',
    'Creating a CI from asset uses the model’s CI class. Wrong class selected on the model. Symptom?',
    [
      'No CI is ever created',
      'IRE/health rules for the intended class never apply; attributes missing; discovery may create a second CI of the right class',
      'The asset is deleted',
      'Serial number is cleared',
    ],
    1,
    'Model category → CI class mapping is HAM+CMDB glue. Fix the model, don’t keep scripting class in a BR.',
    'hard',
  ),
  mcq(
    'ast-t12',
    'In use without assigned_to',
    'Should a BR abort install_status=1 when assigned_to is empty?',
    [
      'Never; shared infrastructure assets (racks, UPSs) may be In use without a person',
      'Always abort; HAM forbids it',
      'Only abort on alm_consumable',
      'assigned_to is mandatory at dictionary level OOTB for all assets',
    ],
    0,
    'Process nuance. Laptops yes; datacenter hardware no. Condition the BR on model category.',
    'hard',
  ),
  mcq(
    'ast-t13',
    'Retirement and licenses',
    'Retiring a workstation asset but SAM still counts an install. Why?',
    [
      'SAM always uses alm_hardware.install_status only',
      'Software installations/discovery on the CI may still be active; retire the CI/uninstall or SAM will keep entitlements consumed',
      'Retirement deletes all cmdb_sam tables',
      'You must use SOAP to notify SAM',
    ],
    1,
    'HAM retire ≠ SAM uninstall. Cross-product interview.',
    'hard',
  ),
  mcq(
    'ast-t14',
    'Stockroom transfer',
    'Two-step transfer (in transit) vs direct stockroom change on the record. Why do HAM people care?',
    [
      'No difference',
      'In-transit states keep inventory accurate and audit who held the device; a silent stockroom overwrite loses chain of custody',
      'Stockroom cannot change after insert',
      'Transfers are only catalog items',
    ],
    1,
    'Asset audits fail when techs edit stockroom like a string field.',
    'hard',
  ),
  mcq(
    'ast-t15',
    'Event asset.assigned',
    'You fire gs.eventQueue on assigned_to change but emails go to the previous user. Cause?',
    [
      'Events cannot include parm1',
      'BR After vs Before: parm built from previous vs current; notification uses event parm or current at send time — classic off-by-one on who is “new assignee”',
      'assigned_to cannot be in events',
      'You must use SOAPMessageV2 for email',
    ],
    1,
    'After BR sees committed current. If the notification script reads previous, you notify the wrong person. Print both sys_ids in the event parms explicitly.',
    'hard',
  ),
];
