import { mcq } from './helpers.js';

export const theory = [
  mcq(
    'chg-t01',
    'Change model vs type',
    'CIS-ITSM: What is the modern distinction between change type (standard/normal/emergency) and a change model?',
    [
      'They are identical; model is a deprecated synonym for type',
      'Type is a coarse classification; a change model is the configurable lifecycle (states, UI, approvals, risk) used to implement that process — standard changes are often models/templates in a catalog, not just type=standard',
      'Change models only exist for Release Management',
      'Emergency changes cannot use a model',
    ],
    1,
    'Tokyo+ interviews: Change Models drive the experience. “Standard” in ITIL is pre-authorized repeatable work — in Now that is typically a Standard Change template/catalog item that creates a change with a model, not a user freely setting type=standard on a blank record.',
    'hard',
  ),
  mcq(
    'chg-t02',
    'Conflict detection',
    'Two changes share a CI and overlapping planned windows. Where does ServiceNow detect this and what is it not?',
    [
      'It is an IRE duplicate CI merge',
      'Change conflict / collision detection (affected CIs, services, windows) — a warning/process control, not a database unique index that blocks insert by default in all configurations',
      'It is only an email from CAB',
      'GlideRecord.addQuery cannot see dates, so conflicts are impossible to script',
    ],
    1,
    'CIS: know conflict detection exists on the change form/related lists, uses CI relationships and schedule, and is configurable. Do not confuse with CMDB identification. Emergency changes may still conflict — process might override.',
    'hard',
  ),
  mcq(
    'chg-t03',
    'Risk calculator vs assessment',
    'Risk is High even though impact is 3. What should an implementer inspect?',
    [
      'Only the client script that sets risk = impact',
      'Change risk conditions, risk assessment questionnaire scores, properties, and whether a BR/flow overwrites the calculated risk after assess',
      'MID Server ECC queue',
      'Knowledge user criteria',
    ],
    1,
    'OOTB risk is not a single field mapping. Risk Assessment (questions) plus condition-based risk values plus manual override. Interview: never hard-code risk in a BR if the customer uses the assessment engine.',
    'hard',
  ),
  mcq(
    'chg-t04',
    'Emergency vs Standard authorization',
    'Who should be allowed to create Emergency changes, and what happens to CAB?',
    [
      'Any itil user; CAB is skipped with no audit',
      'A tight role (change manager / ECAB path): CAB may be bypassed for authorization speed, but post-implementation review / retrospective CAB is the ITIL/Now expectation',
      'Only mid_server users',
      'Emergency is just Normal with type flipped in a client script',
    ],
    1,
    'Emergency is not “no governance.” It is an alternate approval path (CAB chair/ECAB). Server ACLs/BRs must enforce who can set type/model. Client hiding the choice is insufficient.',
    'hard',
  ),
  mcq(
    'chg-t05',
    'GlideDateTime and TZ',
    'A Before BR compares start_date and end_date with string < comparison on getValue() (UTC internal). The customer is in US/Pacific. What’s the bug?',
    [
      'There is no bug; internal values are already local',
      'Lexical string compare can be OK for identical formats, but mixing getDisplayValue() (user TZ) with getValue() (UTC internal) or ignoring empty dates causes false aborts; GlideDateTime.compareTo is the safe API',
      'Dates must be compared only in client scripts',
      'end_date is a duration field so compareTo never works',
    ],
    1,
    'Internal glide_date_time is UTC. Display is user TZ. Mixing them is a classic defect. compareTo, or convert both to GlideDateTime. Also gs.nil both dates before compare.',
    'hard',
  ),
  mcq(
    'chg-t06',
    'Standard Change Catalog',
    'A fulfiller sets type=standard on a blank change_request and expects auto-approval. Why might OOTB-style implementations refuse?',
    [
      'Standard is not a legal type',
      'Standard changes are supposed to originate from approved templates (pre-authorized catalog); a free-typed standard is a control bypass',
      'Standard changes cannot have CIs',
      'Auto-approval requires SOAP',
    ],
    1,
    'CIS: Standard Change Catalog / templates capture CAB pre-approval. Interview answer: don’t let users self-declare standard. Restrict with UI + server.',
    'hard',
  ),
  mcq(
    'chg-t07',
    'change_task types',
    'Implementation, testing, and backout as change_task rows vs one work_note. Why does the exam care?',
    [
      'change_task is deprecated',
      'Tasks are assignable, reportable, and can gate parent state; a single journal cannot prove backout was owned',
      'Backout must be a separate change_request always',
      'Testing tasks must live on sc_task',
    ],
    1,
    'Close completeness: don’t close the change while implementation tasks are open (BR). Task types (implementation, testing, review) are process evidence for audit.',
    'hard',
  ),
  mcq(
    'chg-t08',
    'CAB workbench',
    'CAB date definitions are used for what implementation purpose?',
    [
      'To store the CI warranty date',
      'To define when CAB meetings occur so changes can be associated to a CAB agenda/date rather than a free-text “Thursday”',
      'To pause SLAs on changes',
      'To name the MID Server',
    ],
    1,
    'CIS overlooked topic: CAB Workbench, CAB Definition, agenda. Not just “approver_user on sysapproval_approver.”',
    'hard',
  ),
  mcq(
    'chg-t09',
    'Blackout vs maintenance',
    'outside_maintenance / blackout calendars. A change in a blackout still saved. Why?',
    [
      'Blackout is display-only CSS',
      'Conflict/blackout is often a warning unless you add a Data Policy/BR to abort; configuration determines hard vs soft gate',
      'Blackouts only apply to standard changes',
      'Blackouts are evaluated only by Discovery',
    ],
    1,
    'Implementers must choose warn vs block. Emergency may be allowed in blackout by policy. Don’t assume OOTB hard-stops every window clash.',
    'hard',
  ),
  mcq(
    'chg-t10',
    'Normal change approvals',
    'High-risk Normal change has no approvers generated. Where do you look?',
    [
      'Only the email properties',
      'Approval rules / flow on the change model, assignment group empty, user without approver_user, and whether risk was still Low when the approval activity ran',
      'The ECC queue',
      'Import set coalesce',
    ],
    1,
    'Timing: if risk is calculated After the approval flow already branched, you get no CAB. Order of BRs vs Flow is an interview favorite.',
    'hard',
  ),
  mcq(
    'chg-t11',
    'Caused by / PRB / INC',
    'change_request.caused_by / parent relationships. A change is the permanent fix for a problem. Correct linking?',
    [
      'Only email the problem number in short_description',
      'Relate the change to the problem (and incidents as needed) so you can report “changes that closed problems” — don’t rely on text',
      'Set parent_incident on the change table (that field is on change OOTB as the main key)',
      'IRE createOrUpdateCI with class change_request',
    ],
    1,
    'Use reference fields / related lists (varies by family: rfc on problem, caused_by, etc.). Text in short_description is not a CMDB/process link.',
    'hard',
  ),
  mcq(
    'chg-t12',
    'updateMultiple on tasks',
    'Closing leftover change_task with updateMultiple() after parent cancel. Risk?',
    [
      'updateMultiple cannot set state',
      'Engines/BRs on each task may not run as you expect; you may skip notifications that were required; also easy to forget the query filter and close the whole table',
      'updateMultiple only works in client scripts',
      'It automatically respects ACLs like GlideRecordSecure',
    ],
    1,
    'updateMultiple is a bulk SQL-like update. Combine with setValue then updateMultiple, or loop with setWorkflow(false). Double-check addQuery. Interview: know the API and its foot-guns.',
    'hard',
  ),
  mcq(
    'chg-t13',
    'itil vs change_manager',
    'Why shouldn’t every itil user be change_manager?',
    [
      'itil cannot open change_request at all OOTB',
      'change_manager is a process role for models, properties, CAB configuration — SoD: requesters/fulfillers vs people who can weaken approval',
      'change_manager is only for Discovery',
      'The roles are equivalent if you have sn_change_write',
    ],
    1,
    'CIS role lists exist for a reason. Granting change_manager to the service desk is how standard-change controls die.',
    'hard',
  ),
  mcq(
    'chg-t14',
    'Schedule vs actual',
    'work_start/work_end vs start_date/end_date (names vary by family). Implementation concern?',
    [
      'There is only one date pair on change_request',
      'Planned window drives conflict/CAB; actual start/end drive KPIs. Copying one onto the other in a BR without process agreement breaks both conflict detection and MTTR-style reports',
      'Actual dates are display-only and never stored',
      'You should always setWorkflow(false) when setting dates',
    ],
    1,
    'Know planned vs actual. Don’t “helpfully” stamp actual=planned on insert. Don’t run conflict on actuals.',
    'hard',
  ),
  mcq(
    'chg-t15',
    'Flow vs BR for approvals',
    'Customer wants risk-based approvals. Interview preference?',
    [
      'Always a 2,000-line Before BR generating sysapproval_approver rows',
      'Change model / Flow Designer / Approval rules — code only for gaps — so upgrades and CAB workbench keep working',
      'Client onSubmit that POSTs to sysapproval_approver via GlideAjax only',
      'Import set on each save',
    ],
    1,
    'Configuration over code. Custom BR approvals often skip the workbench and break on family upgrades. Script Includes for reusable predicates, not the whole engine.',
    'hard',
  ),
];
