import { mcq } from './helpers.js';

export const theory = [
  mcq('req-t01', 'Request tables', 'Which table is the catalog request header (REQ)?', ['sc_req_item', 'sc_request', 'sc_task', 'sc_cat_item'], 1, 'sc_request is REQ; sc_req_item is RITM; sc_task is catalog task.', 'easy'),
  mcq('req-t02', 'RITM', 'sc_req_item represents:', ['A catalog item definition', 'One requested item on a request', 'An approval history row only', 'A knowledge feedback row'], 1, 'Each ordered item becomes a RITM under the request.', 'easy'),
  mcq('req-t03', 'Catalog item', 'The catalog item definition table is:', ['sc_item_option', 'sc_cat_item', 'item_option_new', 'sc_request'], 1, 'sc_cat_item is the item; variables are item_option_new; values are sc_item_option.', 'easy'),
  mcq('req-t04', 'requested_for', 'On sc_request, requested_for is:', ['Always the fulfiller', 'The user the request is for', 'The assignment group', 'The catalog manager'], 1, 'Who should receive the service, which may differ from opened_by.', 'easy'),
  mcq('req-t05', 'Close order', 'Best practice when closing a RITM is:', ['Close the RITM first even if catalog tasks are open', 'Close or complete catalog tasks, then the RITM, then the request', 'Delete open sc_task rows', 'Set the request to closed without checking RITMs'], 1, 'Children first, then parent request.', 'intermediate'),
  mcq('req-t06', 'Variables', 'User-entered catalog variable values are stored primarily in:', ['sys_properties', 'sc_item_option (linked to the RITM)', 'incident.work_notes', 'ecc_queue'], 1, 'sc_item_option holds values; item_option_new is the variable definition.', 'intermediate'),
  mcq('req-t07', 'Stage', 'RITM stage (for example fulfillment) is used to:', ['Replace state entirely in all reports', 'Show process progress in the request lifecycle', 'Store price', 'Identify the MID Server'], 1, 'Stage is a process progress indicator.', 'easy'),
  mcq('req-t08', 'Approvals', 'sysapproval_approver.state = approved means:', ['The catalog item was unpublished', 'That approval record was approved', 'All RITMs are closed', 'The request was cancelled'], 1, 'Each approver row has its own state.', 'easy'),
  mcq('req-t09', 'Client quantity', 'Validating quantity <= 5 on submit should use:', ['GlideRecord in an onLoad script with getXMLWait', 'onSubmit + g_form.getValue("quantity")', 'A Scripted REST API only', 'SOAPMessageV2'], 1, 'Client onSubmit for UX; add a server check too if it matters.', 'easy'),
  mcq('req-t10', 'GlideAggregate groupBy', 'groupBy("cat_item") on sc_req_item COUNT answers:', ['How many variables a user filled', 'How many RITMs were ordered per catalog item', 'The price of each item', 'Open incident count'], 1, 'It groups requested items by catalog item.', 'intermediate'),
  mcq('req-t11', 'Cart vs GlideRecord', 'Inserting sc_request/sc_req_item with GlideRecord (vs Cart API) is:', ['The only supported method', 'Possible but you must set relationships (request, cat_item) correctly', 'Impossible on sc_req_item', 'Required for standard changes'], 1, 'Cart/Record Producer APIs handle more of the model; raw insert is possible.', 'intermediate'),
  mcq('req-t12', 'Hardware group', 'Fulfillment assignment_group is often set from:', ['The caller VIP flag only', 'Catalog item/workflow or a named group lookup', 'The incident priority matrix', 'IRE'], 1, 'Assignment comes from the catalog model or routing rules.', 'easy'),
  mcq('req-t13', 'VIP requests', 'requested_for.vip=true in an encoded query finds:', ['VIP catalog items', 'Requests whose requested_for user is VIP', 'Approvers who are VIP', 'Published knowledge'], 1, 'Dot-walk the requested_for reference.', 'easy'),
  mcq('req-t14', 'Events', 'sc.request.opened is typically fired:', ['From a client onChange of price', 'When a request is opened/inserted (event or BR)', 'Only from IntegrationHub', 'When CMDB identification runs'], 1, 'Notifications subscribe to such events.', 'easy'),
  mcq('req-t15', 'Cancel tasks', 'Closing leftover sc_task as Closed Incomplete is done because:', ['Tasks cannot be cancelled', 'The RITM was cancelled or no longer needs fulfillment work', 'It converts them to incidents', 'It publishes knowledge'], 1, 'Keep the task table consistent with parent cancellation.', 'intermediate'),
];
