import { mcq } from './helpers.js';

export const theory = [
  mcq(
    'prb-t01',
    'Incident vs Problem purpose',
    'A major outage is restored by reboot, but the CI fails every Friday. Interview: what records should exist and why?',
    [
      'Only keep the incident open until the Friday failure never happens',
      'Close/resolve incidents when service is restored; open/maintain a Problem for root cause and a Known Error/workaround so future incidents can be diagnosed faster',
      'Convert every incident into a change_request automatically',
      'Problems cannot exist while any related incident is active',
    ],
    1,
    'ITIL/ITSM implementation: Incident = restore service. Problem = cause. Workaround lives on the problem (and often a KE article). Closing incidents is correct after restoration; the problem stays open until a permanent fix (often a change). CIS-ITSM expects this split, not “one ticket for everything.”',
    'hard',
  ),
  mcq(
    'prb-t02',
    'Known Error vs Knowledge',
    'What is the precise relationship in ServiceNow ITSM (not just ITIL slogans)?',
    [
      'Known Error is a separate table that replaces kb_knowledge',
      'A Known Error is a Problem in a known-error-like state/flag, typically with a documented workaround and often a knowledge article in the KEDB — knowledge is the communication artifact, the problem is the process record',
      'Publishing any KB article automatically creates a problem',
      'Known Error articles must not be linked to incidents',
    ],
    1,
    'KEDB is the operational store of workarounds for known errors. In Now, that is problem lifecycle (known_error / knowledge links) plus kb_knowledge visibility via user criteria. Do not invent a second CMDB. Agents attach knowledge to incidents; problem remains the RCA vehicle.',
    'hard',
  ),
  mcq(
    'prb-t03',
    'When to open a problem',
    'CIS-ITSM detection methods: which is the weakest reason to create a Problem?',
    [
      'Trend analysis: many incidents with the same CI/symptom',
      'Post–major incident review identified a systemic cause',
      'A single P4 password reset with no recurrence pattern',
      'Vendor confirms a defect in a version you cannot patch yet (workaround exists)',
    ],
    2,
    'Problems are for unknown/systemic cause or known defects needing tracking. A one-off service request–like incident is not a problem. Recurring incidents, MIM PIR, and vendor KEDs are textbook triggers.',
    'hard',
  ),
  mcq(
    'prb-t04',
    'problem_id vs first_reported_by_incident',
    'Why does the data model have both incident.problem_id and problem.first_reported_by_incident?',
    [
      'They are aliases; ServiceNow stores the same sys_id twice for redundancy',
      'problem_id on each incident is the many-to-one link; first_reported_by_incident preserves the original reporting incident even after later tickets are attached',
      'first_reported_by_incident is the knowledge article',
      'problem_id is only used by Change Management',
    ],
    1,
    'Many incidents can point at one problem. The “first reported” reference is historical and should not be overwritten when you relate newer incidents. Reporting on “how the problem was found” uses the first-reported field.',
    'hard',
  ),
  mcq(
    'prb-t05',
    'Problem tasks',
    'A coordinator assigns a RCA task to App and a vendor task to Network. Why not dump both into problem.work_notes only?',
    [
      'work_notes cannot be used on problem',
      'problem_task (extends task) gives independent assignment, SLAs, and state so investigation is trackable; work_notes are not assignable work items',
      'Problem tasks replace the problem record when closed',
      'Only change_task may be used for RCA',
    ],
    1,
    'CIS-ITSM: problem tasks are first-class work. Interviewers look for SLAs on investigation, not a diary. Closing the parent while tasks are open is a process smell you often block with a BR.',
    'hard',
  ),
  mcq(
    'prb-t06',
    'Closing a problem while incidents are open',
    'Best implementation judgment?',
    [
      'Always allow it; incidents are unrelated after restore',
      'Usually warn or block: either relate/close incidents with the workaround/fix, or keep the problem open — closing hides an unresolved cause from the queue',
      'Automatically delete related incidents',
      'Move all open incidents to Closed Incomplete via updateMultiple without notes',
    ],
    1,
    'You can technically close a problem with open incidents, but implementation specialists add quality gates: copy fix/workaround, communicate, then close children or leave problem Fix in Progress. Silent close is an audit failure.',
    'hard',
  ),
  mcq(
    'prb-t07',
    'Query BR hiding problems',
    'itil users cannot list Closed problems because of a Query BR. A Script Include generating a KEDB widget also uses GlideRecord as the user. Result?',
    [
      'Script Includes always run as system and ignore Query BRs',
      'The widget will also omit closed known errors unless you query as a privileged account or GlideRecord in a scope that bypasses that BR’s condition',
      'Query BRs never apply to problem, only incident',
      'addEncodedQuery bypasses Query BRs',
    ],
    1,
    'Same engine as incident Query BRs. KEDB reports that “lose” retired/closed KE articles/problems are often this. Design the BR condition (roles, gs.getSession().isInteractive()) so integrations and widgets still work.',
    'hard',
  ),
  mcq(
    'prb-t08',
    'Workaround vs permanent fix',
    'Incident is restored with a workaround from the problem. The problem should be:',
    [
      'Closed immediately because service is up',
      'Left open (or Known Error) until a change/permanent fix is verified; incidents may close',
      'Converted into a standard change automatically',
      'Deleted to avoid duplicate CIs',
    ],
    1,
    'Workaround ≠ root cause eliminated. Problem closure criteria = cause addressed and residual risk accepted. Linking rfc/change_request is the usual permanent-fix path.',
    'hard',
  ),
  mcq(
    'prb-t09',
    'Duplicate problems',
    'Two coordinators open problems on the same cmdb_ci the same day. What is the robust check (not just short_description equals)?',
    [
      'sys_id collision will prevent the second insert',
      'Query active problems on the same CI (and optionally normalized short description/category) before insert; optionally a BR abort or relate as duplicate',
      'Only email subject uniqueness is supported',
      'IRE will merge problems automatically',
    ],
    1,
    'IRE is for CMDB, not problem. Duplicates are process + script/flow. Match CI + active + time window. Relating as duplicate keeps metrics honest.',
    'hard',
  ),
  mcq(
    'prb-t10',
    'Roles',
    'Which role is the specialized problem process owner rather than generic itil?',
    [
      'catalog_admin',
      'problem_manager / problem_coordinator (plus sn_problem_write as applicable)',
      'ecmdb_admin',
      'mid_server',
    ],
    1,
    'CIS table of roles: problem_admin, problem_manager, problem_coordinator, problem_task analyst. itil can work tickets; process design uses the problem_* roles. Don’t grant admin to “fix the related list.”',
    'hard',
  ),
  mcq(
    'prb-t11',
    'Copying fix to incidents',
    'A BR on problem copies fix_notes to all related incidents with setWorkflow(false). What can still go wrong?',
    [
      'Nothing; setWorkflow(false) is always safe',
      'You skip incident notifications/SLA reactions the business wanted, and you may still recurse if you forget to filter problem_id or run on every problem update',
      'setWorkflow(false) deletes journal history',
      'Incidents cannot receive comments from server scripts',
    ],
    1,
    'Condition: only when fix_notes changes / state to Resolved. Filter related incidents. Decide whether callers should be notified (maybe setWorkflow true on a second pass). Journals vs comments field choice matters for customer-visible text.',
    'hard',
  ),
  mcq(
    'prb-t12',
    'Assess without workaround',
    'Why do mature implementations abort Assess if workaround is empty?',
    [
      'Assess is a client-only UI policy with no server analog',
      'State model quality gate: you should not claim the problem is understood enough to assess without at least a workaround or explicit “none / investigating” policy',
      'The database forbids empty journal fields',
      'CAB requires workaround on problems',
    ],
    1,
    'CIS process: New → Assess → Root Cause Analysis → Fix in Progress → Resolved. Empty workaround while broadcasting “we understand it” is a KPI lie. Enforce server-side, not only UI.',
    'hard',
  ),
  mcq(
    'prb-t13',
    'Trend analysis',
    '“Three incidents same CI in seven days create a problem.” Where should that live?',
    [
      'A Display BR on incident form',
      'Scheduled job / Flow / PA indicator + event, not a synchronous After BR that queries the world on every incident insert',
      'A UI Action only',
      'Discovery sensor',
    ],
    1,
    'After BR on every incident insert that GlideAggregates 7 days of history will not scale. Async detection is the implementation answer. Deduplicate so you don’t open 50 problems.',
    'hard',
  ),
  mcq(
    'prb-t14',
    'kb_use vs problem',
    'kb_use tracks article attach/view. A manager asks why attaching a KE article to an incident did not close the problem. You say:',
    [
      'kb_use always closes the problem via OOTB BR',
      'Using knowledge on an incident does not complete problem RCA; they are related but independent lifecycles',
      'kb_use is only for catalog items',
      'You must attach the article to the change instead',
    ],
    1,
    'kb_use is telemetry. Problem closure is a human/process decision. Linking knowledge helps the next incident; it is not a state machine for problem.',
    'hard',
  ),
  mcq(
    'prb-t15',
    'Global Business Rule vs Script Include',
    'A “global” BR (table Global) holds a function used by problem scripts. Why do interviews call this a bad 2012 pattern?',
    [
      'Global BRs cannot access GlideRecord',
      'They load broadly with little condition/table scoping; Script Includes load on demand and are the reusable-code vehicle',
      'Script Includes cannot be called from BRs',
      'Global BRs are the only way to share code in scoped apps',
    ],
    1,
    'Docs: prefer Script Includes over Global BRs. Scoped apps use script includes + exports. Global BRs hurt instance performance and upgrade safety.',
    'hard',
  ),
];
