import { mcq } from './helpers.js';

export const theory = [
  mcq('chg-t01', 'Change table', 'Normal/standard/emergency changes are stored on:', ['change_task', 'change_request', 'std_change_record', 'incident'], 1, 'change_request is the change header; change_task holds implementation tasks.', 'easy'),
  mcq('chg-t02', 'Change types', 'Which type is intended for pre-authorized, low-risk, repeatable changes?', ['Emergency', 'Normal', 'Standard', 'Latent'], 2, 'Standard changes follow a pre-approved template/model.', 'easy'),
  mcq('chg-t03', 'Emergency change', 'Emergency changes are used when:', ['You want to skip CMDB updates forever', 'A change must be made urgently to restore or protect service', 'The requester is VIP', 'The CI has no owner'], 1, 'Emergency is for urgent risk reduction/restoration, with tighter controls afterward.', 'easy'),
  mcq('chg-t04', 'CAB', 'CAB stands for:', ['Change Assignment Board', 'Change Advisory Board', 'Configuration Asset Bundle', 'Closed After Backout'], 1, 'CAB reviews higher-risk changes.', 'easy'),
  mcq('chg-t05', 'Planned window', 'start_date after end_date on a change should be:', ['Ignored by the platform', 'Rejected by a data policy or Business Rule', 'Converted to emergency automatically', 'Stored as a duration only'], 1, 'Validate planned start/end with GlideDateTime.compareTo.', 'intermediate'),
  mcq('chg-t06', 'change_task', 'Implementation, testing, and backout work is typically tracked on:', ['sc_task', 'change_task', 'incident_task', 'problem_task'], 1, 'change_task.change_request points to the parent change.', 'easy'),
  mcq('chg-t07', 'Risk field', 'Change risk is commonly influenced by:', ['Only the caller VIP flag', 'Impact, type, CI criticality, and similar factors', 'Knowledge article word count', 'MID Server name'], 1, 'Risk models combine impact and other attributes.', 'intermediate'),
  mcq('chg-t08', 'Blackout', 'A change blackout window means:', ['The instance is in read-only mode', 'Changes should not be scheduled in that period', 'All SLAs pause', 'CMDB discovery stops'], 1, 'Blackouts block or warn on conflicting schedules.', 'easy'),
  mcq('chg-t09', 'Workflow skip', 'setWorkflow(false) on change tasks is used when closing children to:', ['Grant itil_admin', 'Avoid recursive BR/workflow on each task update', 'Send more emails', 'Bypass the CAB permanently'], 1, 'Bulk close without re-firing engines.', 'intermediate'),
  mcq('chg-t10', 'GlideDateTime', 'compareTo returns < 0 when:', ['The dates are equal', 'This date/time is before the other', 'This date/time is after the other', 'The value is not a date'], 1, 'Negative means earlier than the compared GlideDateTime.', 'intermediate'),
  mcq('chg-t11', 'Standard CAB', 'Why might cab_required be set false for standard changes?', ['Standard changes never have CIs', 'They are pre-approved so CAB is not required every time', 'Emergency always skips CAB too', 'CAB is a client-only field'], 1, 'Process: standard = pre-authorized.', 'easy'),
  mcq('chg-t12', 'Unauthorized emergency', 'Restricting who can set type=emergency is usually enforced with:', ['UI Policy only, which the API ignores', 'Business Rule / ACL / role checks on the server', 'CSS', 'A MID Server'], 1, 'Server rules and ACLs, not just client scripts.', 'intermediate'),
  mcq('chg-t13', 'Related from catalog', 'A catalog RITM can seed a change by copying:', ['sc_cat_item price only', 'short_description, CI, and requested_for → requested_by', 'Only the sys_id of the catalog item into number', 'Knowledge workflow_state'], 1, 'Common fulfillment pattern: RITM data onto change_request.', 'intermediate'),
  mcq('chg-t14', 'onSubmit high risk', 'Requiring cab_recommendation when risk is high is typically a:', ['Transform map', 'Client onSubmit or UI Policy plus server validation', 'Discovery schedule', 'Import set'], 1, 'Client UX plus server enforcement is best practice.', 'easy'),
  mcq('chg-t15', 'Count changes on a CI', 'The efficient way to count changes for a CI in the last 30 days is:', ['query() every change and increment a JS counter', 'GlideAggregate COUNT with cmdb_ci and sys_created_on >= gs.daysAgo(30)', 'g_form.getRowCount()', 'REST to instance homepage'], 1, 'Use GlideAggregate and date filters.', 'intermediate'),
];
