import { mcq } from './helpers.js';

export const theory = [
  mcq(
    'req-t01',
    'REQ / RITM / TASK',
    'An order guide creates one REQ with three items. Two items are fulfilled; one is waiting on approval. What is the correct state model thinking?',
    [
      'The REQ must be Closed Complete because most items are done',
      'REQ stays open while any RITM is active; each RITM/sc_task has its own state/stage; closing the REQ while a RITM is in approval is a process bug',
      'sc_task always closes the REQ directly, skipping RITM',
      'Order guides cannot create multiple RITMs',
    ],
    1,
    'CIS request fulfillment: Request is the cart header. RITMs are independently fulfilled (often different groups). Stage on RITM is not the same as state. Don’t auto-close REQ on first RITM complete.',
    'hard',
  ),
  mcq(
    'req-t02',
    'Cart API vs GlideRecord insert',
    'A Scripted REST “order a laptop” inserts sc_request and sc_req_item with GlideRecord but variables and approvals never appear. Why?',
    [
      'REST cannot create catalog records',
      'Raw inserts skip Cart/Record Producer/Flow processing (price, variables, approvals, requested_for cascade). Use CartJS / Cart API / Flow / the Service Catalog REST APIs',
      'You must set number manually to REQ1',
      'Variables only exist on incident',
    ],
    1,
    'Community classic: GlideRecord into sc_req_item does not run the catalog engine. Missing sc_item_option rows, no workflow, wrong stage. Interview: name CartJS (or current family equivalent) and why.',
    'hard',
  ),
  mcq(
    'req-t03',
    'Variable storage',
    'You need the “quantity” value in a Business Rule on sc_task. Naive current.quantity fails. Correct model?',
    [
      'quantity is always on sc_task OOTB',
      'Variables are item_option_new definitions; values are sc_item_option / sc_item_option_mtom linked to the RITM — query those or use the Variable API / ritm.variables.quantity in server scripts where supported',
      'They are only in g_form and never stored',
      'They are stored in ecc_queue',
    ],
    1,
    'Don’t add a custom quantity field on sc_task unless you copy it. Multi-row variables are even more tables (sc_multi_row_question_answer). Interviewers fail people who “addQuery quantity on sc_task.”',
    'hard',
  ),
  mcq(
    'req-t04',
    'User criteria vs ACL',
    'A user cannot see a catalog item. Catalog client says “ACL is fine, they have itil.” Next checks?',
    [
      'Only snc_read on sc_cat_item',
      'User Criteria on the item/category/catalog (Available For / Not Available For), including both match and not-match, and whether “Match All” is set — this is separate from table ACLs',
      'MID Server status',
      'Whether the item is a change model',
    ],
    1,
    'CIS: user criteria is the catalog visibility engine. itil does not mean every item. “Not Available For” a group the user belongs to hides the item even if Available For is Everyone.',
    'hard',
  ),
  mcq(
    'req-t05',
    'Approval on RITM vs REQ',
    'Cost-based approval: $50 item vs $5,000 item on the same REQ. Where should the approval sit?',
    [
      'Only on the REQ so one manager approves the cart total once, always',
      'Usually on the RITM (or a mix): items have different owners/cost; a single REQ approval can under- or over-control. Know your Flow is bound to which table',
      'Approvals can only be on sc_task',
      'Catalog items cannot have approvals',
    ],
    1,
    'Implementation choice. Cart-level approval is simpler; item-level is correct for different CIs/cost centers. If Flow triggers on sc_request, expensive items can slip through a cheap-cart rule.',
    'hard',
  ),
  mcq(
    'req-t06',
    'requested_for cascade',
    'You change requested_for on the REQ after insert. RITM still shows the old user. Why?',
    [
      'requested_for exists only on RITM, never REQ',
      'OOTB may copy requested_for to RITM on insert but not keep them in sync unless a BR/flow does; don’t assume cascade',
      'The platform always syncs them in Display BRs only',
      'You must use SOAP to sync',
    ],
    1,
    'Data model trap. Test the family behavior; many customers add a BR. Notifications key off different fields on REQ vs RITM.',
    'hard',
  ),
  mcq(
    'req-t07',
    'Order guides',
    'What problem do order guides solve that a single catalog item with 40 variables does not?',
    [
      'They remove the need for sc_task',
      'They bundle multiple items with rule-based inclusion (e.g. laptop + headset + access) as separate RITMs with separate fulfillment',
      'They replace the CMDB',
      'They are only for knowledge',
    ],
    1,
    'CIS request patterns: order guide vs record producer vs item. Record producer targets an arbitrary table (often incident). Order guide = multiple items.',
    'hard',
  ),
  mcq(
    'req-t08',
    'Record producer vs catalog item',
    'HR wants “Report an issue” to create an incident, not a RITM. Correct artifact?',
    [
      'sc_cat_item that fulfills to sc_task only',
      'Record Producer (or similar) targeting incident — not a fulfillment item that creates REQ/RITM unless you build a custom flow to convert',
      'Standard change template',
      'Import set on kb_knowledge',
    ],
    1,
    'Interview: producers vs items. Using a generic item and then a BR that inserts incident and cancels the RITM is a hack that breaks reporting.',
    'hard',
  ),
  mcq(
    'req-t09',
    'sc_task generation',
    'A RITM sits in fulfillment with zero catalog tasks. Typical causes?',
    [
      'sc_task is not a real table',
      'No workflow/flow/execution running, flow error, approval not complete so fulfillment never started, or the item is a producer not a fulfillment item',
      'You need a MID Server to create tasks',
      'Tasks only generate if quantity > 5',
    ],
    1,
    'Debug: workflow context, Flow execution, approval state, catalog item process engine (flow vs workflow). Don’t write a BR that inserts sc_task on every RITM unless you own that design.',
    'hard',
  ),
  mcq(
    'req-t10',
    'Maintain item vs catch-all BR',
    'Every catalog item needs “if location is London, assignment_group = EU Desk.” Prefer?',
    [
      'One global After BR on sc_req_item with 200 if/else item sys_ids',
      'Catalog Data Lookup / assignment in the item flow, or a data-driven lookup table, not a giant BR that must change every time a new item goes live',
      'Client script on the portal only',
      'Query BR that rewrites location to empty',
    ],
    1,
    'Upgrade and catalog_editor independence. Hard-coded sys_ids in a BR are an interview smell.',
    'hard',
  ),
  mcq(
    'req-t11',
    'Two-step vs three-step',
    'Some catalogs hide REQ from users (two-step). Implementation impact?',
    [
      'RITM no longer exists',
      'You still have REQ in the database; reporting, approvals, and scripts that assume users open REQ in the native UI will confuse portal-only users',
      'sc_request table is dropped',
      'Variables move to incident',
    ],
    1,
    'Property-driven checkout. Integrations inserting REQ still need the header. Train fulfillers on which number the customer sees (RITM vs REQ).',
    'hard',
  ),
  mcq(
    'req-t12',
    'GlideAjax price',
    'Showing live price on a catalog client script. Why not GlideRecord the price on the client?',
    [
      'Price is never on sc_cat_item',
      'Client GlideRecord is limited/discouraged; price may need quantity, currency, and discounts computed server-side — GlideAjax or Catalog Data Lookup',
      'Prices can only be retrieved via SOAPMessageV2',
      'g_form.getValue("price") always works on Service Portal',
    ],
    1,
    'Portal widgets != native g_form. Many APIs differ (g_form vs spUtil). Interview: name the UI you are on.',
    'hard',
  ),
  mcq(
    'req-t13',
    'Closing tasks on cancel',
    'User cancels the RITM. Open sc_task remain Work in Progress. What’s the implementation defect?',
    [
      'Expected; tasks never follow parent',
      'Cancel flow must cascade (BR/flow) to sc_task and possibly REQ; otherwise SLAs and workload reports lie',
      'You should delete the user instead',
      'Use IRE to retire the tasks',
    ],
    1,
    'Same pattern as change_task. setWorkflow(false) may skip task notifications — decide intentionally.',
    'hard',
  ),
  mcq(
    'req-t14',
    'sysapproval_approver vs asked_to',
    'Approval is “requested” but the manager never got it. Which is NOT the first thing to blame?',
    [
      'Notification/event for approval.inserted disabled or user notification prefs',
      'The GlideRecord API itself cannot insert sysapproval_approver',
      'Approval assigned to a group with no members, or user inactive',
      'Email properties / SMTP',
    ],
    1,
    'Approvals are records. Events fire notifications. Group approvals need members. Don’t start at “ServiceNow approvals are broken.”',
    'hard',
  ),
  mcq(
    'req-t15',
    'Keep vs skip Cart',
    'High-volume integration creates 20k laptop orders/hour. CartJS per call is slow. Community-aligned pattern?',
    [
      '20k CartJS calls in one user transaction',
      'Stage into an import set / queue table, transform asynchronously to catalog APIs or a dedicated fulfillment table; do not run full catalog engine inline per REST thread',
      'updateMultiple on sc_cat_item',
      'Only SOAP can scale',
    ],
    1,
    'Community: Scripted REST should be thin. Import set + transform or async events. Per-row import sets can still explode — batch into one import set if you go that route.',
    'hard',
  ),
];
