import { mcq } from './helpers.js';

export const theory = [
  mcq('acl-t01', 'ACL evaluation order', 'Record ACL vs field ACL: a user can open the incident form but SSN is empty/*blank*. Most accurate explanation?', ['The record ACL failed', 'Record read passed; a field ACL on that column denied read so the UI/API omits or blanks the field', 'Query BRs always blank fields', 'g_form.setDisplay is the only way fields blank'], 1, 'Table/record ACL grants the row. Field ACLs are evaluated per column. Deny field read ≠ deny record read. Debug Security Rules shows both layers. Never “fix” this with a client script only.', 'hard'),
  mcq('acl-t02', 'Wildcard table *', 'What does an ACL on *.* vs incident.None mean in interviews?', ['They are identical', '* is a fallback for tables/fields without a more specific ACL; a specific incident ACL wins over * for that table. Empty/incorrect * rules are a common lockout or wide-open hole', '* always denies everything', 'You cannot create * ACLs'], 1, 'Specificity: table.field > table.None > * . Understand None (row) vs field name. Misconfigured * is a classic outage after an update set.', 'hard'),
  mcq('acl-t03', 'Admin override', 'gs.hasRole("itil") returns true for admin even without itil. Why does ACL design still break?', ['Admin never bypasses ACLs', 'Many ACL scripts use hasRole which admin satisfies; security that must not apply to admin needs hasRoleExactly or explicit user_name checks — and admin can still often pass other ACLs. Design SoD knowing admin is a bypass hammer', 'hasRole never returns true for admin', 'Admin cannot query incident'], 1, 'Interview: hasRole vs hasRoleExactly (client g_user too). Don’t use hasRole("snc_internal") style checks expecting admin to fail.', 'hard'),
  mcq('acl-t04', 'Script + role + condition', 'An ACL has a role, a condition, AND a script. When does it pass?', ['If any one of the three is true (OR)', 'Typically ALL configured parts must pass (AND): role AND condition AND script answer true. Empty script is not a free pass if other parts fail', 'Script always overrides roles', 'Conditions are ignored when a script exists'], 1, 'People assume script replaces roles. Debug Security: each piece is a gate. Test with a non-admin.', 'hard'),
  mcq('acl-t05', 'GlideRecord vs ACL', 'Why can a Business Rule using GlideRecord update a field the user cannot edit on the form?', ['BRs cannot update that field', 'Server GlideRecord often runs with engine privileges / not the same as UI field ACL for that user; user-facing paths need GlideRecordSecure or the BR is an intentional elevation — never confuse UI ACLs with scripted writes', 'Field ACLs apply equally to all GlideRecord in every context', 'setWorkflow(false) enforces field ACLs'], 1, 'Elevation vs user context is the whole ACL interview. Integrations running as a privileged user bypass UI. That’s a feature and a finding.', 'hard'),
  mcq('acl-t06', 'Query ACLs', 'Query ACLs / query rules vs Query Business Rules: which statement is right?', ['They are the same record type', 'Both can restrict which rows a user sees in lists/queries; Query BRs mutate the GlideRecord query; ACLs deny access. Using both without planning causes “empty list” tickets that look like a broken filter', 'Query ACLs only apply to SOAP', 'Query BRs replace all ACLs so you should delete ACLs'], 1, 'CIS/CAD: two mechanisms. Debug: impersonate + Debug Security + log the encoded query.', 'hard'),
  mcq('acl-t07', 'Create ACL and isNewRecord', 'Create ACL scripts that check current.number == "INC0001" fail. Why?', ['number is always INC0001 on create', 'On create, many fields are still empty; number may be generated on insert. Use roles, gs.hasRole, or parent fields that exist before insert — not post-insert data', 'Create ACLs cannot use scripts', 'You must use SOAP to create'], 1, 'Create vs write. isNewRecord() is for write ACLs on records not yet saved. Create happens before a sys_id exists in DB.', 'hard'),
  mcq('acl-t08', 'Debug Security Rules', 'Best first tool when “itil cannot see a module/record” after an update set?', ['Rewrite all ACLs from scratch', 'Impersonate the user, enable Debug Security Rules / Debug Business Rules, reproduce, read the first failing ACL — do not guess in sys_security_acl list unsorted', 'Delete the user', 'Client script console.log'], 1, 'Platform tool. Session debug. Impersonation. Then look at roles and groups.', 'hard'),
  mcq('acl-t09', 'UI Policy vs ACL', 'Hiding a field with UI Policy is not security because?', ['UI Policies encrypt the field', 'The value can still be read via API, reports, lists, export, GlideRecord; only ACLs/Data Policies/encryption protect data', 'UI Policies run on the server before SQL', 'Hidden fields are deleted'], 1, 'Repeated ITSM/CAD question. Same as mandatory client scripts.', 'hard'),
  mcq('acl-t10', 'Scoped app ACLs', 'A scoped Script Include queries incident and fails for a user who can open incidents in ITSM. Likely cause?', ['Scoped apps cannot query incident', 'Missing cross-scope privilege / runtime access / ACLs on the script include itself (Execute) — not only table ACLs', 'GlideRecord is banned in scope', 'You must duplicate the incident table in scope'], 1, 'Application access on the table (Can read, Allow access to this table via web services) plus SI protection. CAD territory that hits ITSM integrations.', 'hard'),
  mcq('acl-t11', 'REST Table API', 'Table API honors ACLs of the authenticated user. You used basic auth as admin and thought ACLs were “tested.” Why is that invalid?', ['Table API ignores ACLs always', 'You tested admin, not the integration user; create a dedicated user with least-privilege roles and retest; also test field ACLs on GET sysparm_fields', 'Basic auth disables ACLs', 'Table API only works as guest'], 1, 'Least privilege integration accounts. Field-level exclusions in JSON.', 'hard'),
  mcq('acl-t12', 'answer = true', 'An ACL script is empty / answer never set. What happens?', ['JavaScript throws and the node crashes', 'Platform default for an ACL script without setting answer is typically deny (or legacy quirks) — never rely on implicit true; always set answer explicitly', 'Empty script always allows', 'Empty script skips the ACL row'], 1, 'Be explicit. Interviewers want answer = ... every time.', 'hard'),
  mcq('acl-t13', 'Deny-unless vs allow-if', 'ServiceNow ACLs are closer to which model?', ['Default allow if no ACL exists on a custom table — which is why new tables are wide open until you add ACLs', 'Default deny for every new table with no extra work', 'ACLs cannot be added to custom tables', 'Only admin can create tables so ACLs never matter'], 0, 'Huge CAD trap: custom table with no ACLs can be accessible more than you think depending on * rules. Always add ACLs on new tables. Verify with a non-admin.', 'hard'),
  mcq('acl-t14', 'gs.getSession().impersonate', 'When is impersonate in a script appropriate?', ['In every REST call to skip ACLs', 'Rare, audited elevation (e.g. inbound integration must act as the caller); always restore, never impersonate in a Before BR on a user-facing form as a shortcut', 'To make Query BRs faster', 'Impersonate is client-only'], 1, 'Security review finding if used casually. Prefer GlideRecordSecure as the user already in session.', 'hard'),
  mcq('acl-t15', 'Roles in groups', 'User has itil via group. ACL requires itil. Still fail. Causes?', ['Groups never grant roles', 'Role not in the group, inheritance cache, domain, or the ACL needs a different role (sn_incident_read) while itil was assumed enough', 'ACLs cannot use roles from groups', 'You need SOAP to refresh roles'], 1, 'Check sys_user_has_role. Impersonate. sn_* granular roles in later families vs classic itil.', 'hard'),
  mcq('acl-t16', 'Write ACL vs Data Policy', 'Both can block a field update. Difference?', ['None', 'ACL is security (who); Data Policy is data quality (what is allowed) and can apply to UI and/or web services independently of roles', 'Data Policies only run on the client', 'ACLs cannot block writes'], 1, 'Use both. ACL: HR can write u_ssn. Data Policy: format. Don’t overload ACL scripts with regex validation.', 'hard'),
  mcq('acl-t17', 'List vs form', 'User sees the row in a list but form says Security constraints. Typical?', ['Impossible', 'List used a query that showed the row (or a report as another user); form load evaluates ACLs differently, or a Display BR aborts, or field ACLs on a mandatory field; impersonate on both views', 'Lists never use ACLs', 'Forms ignore ACLs'], 1, 'Debug both. Also UI actions vs form.', 'hard'),
  mcq('acl-t18', 'GlideRecordSecure.next()', 'Secure query returns fewer rows than GlideRecord for the same addQuery. Why?', ['A bug; they must match', 'Unreadable rows are skipped; that is the point. Using Secure then getRowCount for metrics under-counts vs admin GlideRecord', 'Secure ignores addQuery', 'Secure only works on sys_user'], 1, 'Don’t mix Secure counts with admin KPIs. Document the user context.', 'hard'),
  mcq('acl-t19', 'Execute ACL on Script Include', 'Client callable SI works for admin, 403/empty for itil. Besides Client callable checkbox?', ['Nothing else', 'Script Include ACL / roles on the include, and the ACLs on tables it touches; also sandbox and scope', 'itil can never call GlideAjax', 'You must put the SI in Global and uncheck isolation'], 1, 'Three layers: Ajax access, SI roles, table ACLs inside the method.', 'hard'),
  mcq('acl-t20', 'High security plugin / contextual security', 'Why might an instance after “High Security” behave differently for * ACLs?', ['It disables all ACLs', 'High Security / contextual security tightens defaults; copying ACLs from a PDI without it causes surprises. Know whether the customer instance has it before designing * wildcards', 'It only affects MID', 'It removes itil'], 1, 'Environment parity. Interview: don’t design ACLs on a loose PDI and ship to a locked prod.', 'hard'),
];
