import { mcq } from './helpers.js';

export const theory = [
  mcq(
    'cmdb-t01',
    'cmdb vs cmdb_ci',
    'CIS: What extends what?',
    [
      'Everything extends incident',
      'Technical CIs extend cmdb_ci; some non-technical/base configuration items extend cmdb (Base Configuration Item). Mixing them in a GlideRecord("cmdb_ci") query silently drops classes that live only under cmdb',
      'cmdb_ci extends alm_asset',
      'cmdb_rel_ci extends cmdb_ci',
    ],
    1,
    'CSDM/CIS trap. Query the right ancestor. Relationships still live in cmdb_rel_ci.',
    'hard',
  ),
  mcq(
    'cmdb-t02',
    'IRE vs GlideRecord insert',
    'Discovery-quality uniqueness: two payloads with the same serial for a server. What happens with naive insert vs IRE?',
    [
      'GlideRecord insert always coalesces on serial_number OOTB',
      'Blind insert creates duplicates; IdentificationEngine uses identification rules (hardware rule: serial, etc.) and reconciliation to update the right CI and set discovery_source',
      'IRE only works for users, not CIs',
      'addQuery("name") is equivalent to IRE',
    ],
    1,
    'Never integration-insert cmdb_ci_* for authoritative sources. IRE JSON items[].className + values + lookup. Reconciliation decides which source wins a field.',
    'hard',
  ),
  mcq(
    'cmdb-t03',
    'Identification vs reconciliation',
    'Identification succeeded but a field didn’t update from SCCM. Why?',
    [
      'IRE cannot update fields',
      'Reconciliation rules / data source precedence blocked that field from that source; identification only found the CI',
      'You forgot g_form.save()',
      'serial_number is not a field',
    ],
    1,
    'Two engines. Interview: “duplicate CI” vs “stale field.” Different consoles (CI Class Manager identification vs recon).',
    'hard',
  ),
  mcq(
    'cmdb-t04',
    'Dependent identification',
    'An application CI is identified by name + running on a specific server. If you only send name, IRE may create duplicates. Why?',
    [
      'Applications cannot be CIs',
      'Dependent identity uses parent/host lookup rules; incomplete relationship payload fails uniqueness',
      'Name is always globally unique in CMDB',
      'Use problem_id to identify apps',
    ],
    1,
    'IRE payload must include related items (Runs on::Runs) when rules are dependent. Community duplicate-app-CI epidemic.',
    'hard',
  ),
  mcq(
    'cmdb-t05',
    'cmdb_rel_ci direction',
    'Parent = App, Child = Server, type = Runs on::Runs. Is that the OOTB semantic everyone uses?',
    [
      'Direction is arbitrary and never documented',
      'Type is directional (Runs on vs Runs); reversing parent/child inverts the graph and breaks impact/change conflict. Always verify the type’s parent/child descriptors',
      'You should store both directions as two rows always',
      'Relationships are stored on incident',
    ],
    1,
    'Impact calculation and service mapping assume a direction. Wrong direction = wrong blast radius on a change.',
    'hard',
  ),
  mcq(
    'cmdb-t06',
    'Health dashboard duplicate vs orphan',
    'Orphan vs duplicate in CMDB Health mean?',
    [
      'The same thing',
      'Duplicates fail identification uniqueness; orphans fail expected relationships/required fields (depends on health metric) — different remediations',
      'Orphans are always retired CIs',
      'Duplicates are only name collisions in Excel',
    ],
    1,
    'CIS/CSDM operations. Don’t run deleteMultiple on all “orphans” without reading the metric definition.',
    'hard',
  ),
  mcq(
    'cmdb-t07',
    'Querying a class',
    'GlideRecord("cmdb_ci_server") vs GlideRecord("cmdb_ci") + addQuery("sys_class_name", "cmdb_ci_linux_server"). Difference?',
    [
      'Identical always',
      'Querying the class table uses the hierarchy (includes extensions); sys_class_name equals a leaf class excludes other server subclasses unless you use IN or INSTANCEOF-style patterns',
      'sys_class_name cannot be queried',
      'The class table cannot be queried with addQuery',
    ],
    1,
    'INSTANCEOF / table API. Interview: linux vs windows both servers. Wrong filter drops a fleet.',
    'hard',
  ),
  mcq(
    'cmdb-t08',
    'Principal class / CSDM',
    'Why not put a business application as cmdb_ci_linux_server?',
    [
      'You should; one class is simpler',
      'CSDM separates Application Service / Business App / Technical CI. Wrong class breaks service mapping, IRE rules, and ITSM referencing',
      'Business apps cannot have relationships',
      'Linux servers cannot be operational',
    ],
    1,
    'CSDM is on CIS-ITSM now. Class choice is a design decision, not a label.',
    'hard',
  ),
  mcq(
    'cmdb-t09',
    'setWorkflow on CI updates',
    'Data fix sets install_status=7 on 10k CIs with setWorkflow(false). What did you skip that ITSM might need?',
    [
      'Nothing important',
      'BR/flows that retire relationships, notify support groups, sync assets, or fire cmdb events — plus audit/updated_on if autoSysFields(false)',
      'IRE identification always still runs',
      'Client scripts on cmdb_ci will still run',
    ],
    1,
    'Bulk CMDB hygiene vs process. Sometimes you want engines; sometimes you don’t. Say it out loud in the interview.',
    'hard',
  ),
  mcq(
    'cmdb-t10',
    'Asset-CI sync',
    'alm_asset.ci points to a CI; assigned_to diverges. Typical cause?',
    [
      'They cannot be linked',
      'One-direction BRs, import that updates only one side, or model not using the asset-CI field service',
      'assigned_to on CI is not a field',
      'IRE deletes assets nightly',
    ],
    1,
    'ITSM + HAM. Know which product owns assignment. Dual-write without a source of truth = tickets assigned to the wrong person.',
    'hard',
  ),
  mcq(
    'cmdb-t11',
    'Ref qualification on incident.cmdb_ci',
    'Users pick retired CIs. Best control?',
    [
      'Client script only that alerts after submit',
      'Reference qualifier / dictionary advanced qualifier excluding operational_status/install_status, plus a server Data Policy/BR — UI-only filters are bypassed by imports',
      'Delete all retired CIs nightly',
      'Hide cmdb_ci from itil',
    ],
    1,
    'Qualifiers are UX. Imports and REST still need server rules.',
    'hard',
  ),
  mcq(
    'cmdb-t12',
    'Dynamic CI groups vs static',
    'Change conflict on an application service. Why include related CIs?',
    [
      'Conflict only looks at the one reference field',
      'Impacted services/CI relations expand the conflict set; a service CI without relations looks “clean” and is a false negative',
      'Conflict detection ignores CMDB',
      'Only alm_hardware participates in conflict',
    ],
    1,
    'Populate relations or use service mapping. Empty graph = useless collision detection.',
    'hard',
  ),
  mcq(
    'cmdb-t13',
    'createOrUpdateCI source string',
    'Why does IdentificationEngine.createOrUpdateCI("ServiceNow", json) vs "SCCM" matter?',
    [
      'The string is comments only',
      'It is the discovery/reconciliation source name used in rules and cmdb_ci.discovery_source — wrong source applies wrong precedence',
      'It must always be the MID name',
      'It must be a sys_id',
    ],
    1,
    'Match the Data Source record. Typos = unidentified inserts or fields that never win.',
    'hard',
  ),
  mcq(
    'cmdb-t14',
    'GlideRecordSecure on CMDB',
    'An integration user needs to update IPs but not HR CIs. Pattern?',
    [
      'Run as admin and hope',
      'Dedicated integration user + ACLs on classes + GlideRecordSecure in scripted APIs; don’t use maint/admin in REST',
      'Query BRs are the only control',
      'cmdb_ci has no ACLs OOTB so none can be added',
    ],
    1,
    'Least privilege. Class-level ACLs. IRE still needs a user that can write the target class.',
    'hard',
  ),
  mcq(
    'cmdb-t15',
    'deleteMultiple relationships',
    'Retiring a server, deleteMultiple on cmdb_rel_ci where parent OR child = ci. What can you destroy?',
    [
      'Only that server’s rows if the encoded query is correct — still: service maps, app Runs-on, and reverse relations; consider end-dating vs delete for history',
      'The entire CMDB always',
      'Nothing; deleteMultiple is blocked on cmdb_rel_ci',
      'Only orphan duplicates',
    ],
    0,
    'Query must be precise. Some shops expire relationships instead of delete for forensic graphs. Never run unfiltered deleteMultiple in a fix script.',
    'hard',
  ),
];
