import { mcq } from './helpers.js';

export const theory = [
  mcq('prb-t01', 'Problem table', 'Which table stores problem records?', ['incident', 'problem', 'change_request', 'kb_knowledge'], 1, 'Problems live on the problem table (extends task).', 'easy'),
  mcq('prb-t02', 'Purpose of Problem', 'The primary goal of Problem Management is to:', ['Restore service as fast as possible', 'Find root cause and prevent recurrence', 'Approve catalog items', 'Retire CIs'], 1, 'Incident restores service; problem targets cause and prevention.', 'easy'),
  mcq('prb-t03', 'Known error', 'A known error typically means:', ['The problem is still New and unassigned', 'Root cause is understood and a workaround or fix is documented', 'All related incidents are closed automatically', 'The problem must be deleted'], 1, 'Known Error often ties to a knowledge article and workaround.', 'easy'),
  mcq('prb-t04', 'Link from incident', 'Which incident field commonly points to a related problem?', ['parent_incident', 'problem_id', 'rfc', 'caused_by'], 1, 'incident.problem_id references the problem.', 'easy'),
  mcq('prb-t05', 'Problem tasks', 'problem_task records are used to:', ['Replace the problem record', 'Break investigation or fix work into assignable tasks', 'Store SLAs', 'Create catalog variables'], 1, 'Problem tasks track investigation steps.', 'easy'),
  mcq('prb-t06', 'addNullQuery', 'gr.addNullQuery("assigned_to") returns problems where assigned_to is:', ['The current user', 'A group', 'Empty', 'Inactive'], 2, 'addNullQuery matches empty/null field values.', 'easy'),
  mcq('prb-t07', 'Workaround field', 'Where is a workaround commonly stored on a problem?', ['close_code only', 'workaround (and often knowledge)', 'cmdb_ci', 'sys_id'], 1, 'workaround documents temporary relief pending a permanent fix.', 'easy'),
  mcq('prb-t08', 'Relate many incidents', 'Incidents related to one problem are usually queried by:', ['short_description CONTAINS problem number', 'problem_id = problem sys_id', 'caller_id = problem opened_by', 'category = problem'], 1, 'Filter incident.problem_id.', 'easy'),
  mcq('prb-t09', 'Prevent delete', 'Why might a Business Rule abort deleting a problem?', ['Problems cannot have Business Rules', 'Related incidents still reference it', 'GlideRecord cannot delete problems', 'ITIL forbids all deletes'], 1, 'Referential integrity and audit history — block delete if children exist.', 'intermediate'),
  mcq('prb-t10', 'Assess state', 'Moving a problem to Assess without a workaround is often blocked because:', ['Assess requires CAB', 'Process expects investigation notes/workaround before progressing', 'State 2 is Closed', 'Problems cannot be assessed'], 1, 'Quality gates keep incomplete problems out of later states.', 'intermediate'),
  mcq('prb-t11', 'Fix notes to incidents', 'Copying problem fix notes onto related incidents is typically done with:', ['g_form only', 'A server script querying incident.problem_id', 'Import sets', 'MID Server'], 1, 'Server GlideRecord (or Flow) updates linked incidents.', 'intermediate'),
  mcq('prb-t12', 'Duplicate problems', 'A duplicate-problem check usually compares:', ['sys_created_on only', 'Same CI (and often similar short description) among active problems', 'Priority only', 'Caller VIP flag'], 1, 'Same CI plus active problems is a common duplicate signal.', 'intermediate'),
  mcq('prb-t13', 'Client hide field', 'g_form.setDisplay("workaround", false) will:', ['Delete the workaround from the database', 'Hide the field on the current form', 'Hide it for all users in list view permanently', 'Skip ACLs'], 1, 'It is a client form API for the current session/form.', 'easy'),
  mcq('prb-t14', 'OR in encoded query', 'In encoded queries, ^OR means:', ['AND', 'OR the next condition', 'NOT', 'ORDER BY'], 1, '^ is AND; ^OR is OR.', 'easy'),
  mcq('prb-t15', 'first_reported_by_incident', 'This problem field is intended to store:', ['The latest related incident', 'The original incident that raised the problem', 'A knowledge article', 'The CAB date'], 1, 'It preserves the first reporting incident.', 'easy'),
];
