import { mcq } from './helpers.js';

export const theory = [
  mcq('ast-t01', 'Asset vs CI', 'alm_asset is primarily about:', ['Logical running configuration only', 'Financial/lifecycle tracking of an asset, often linked to a CI', 'Only software entitlements in every instance', 'SLA definitions'], 1, 'Assets track ownership, cost, stock; CIs track configuration. They can be linked (ci field).', 'easy'),
  mcq('ast-t02', 'Hardware table', 'alm_hardware extends:', ['incident', 'alm_asset', 'cmdb_rel_ci', 'sc_task'], 1, 'Hardware assets specialize alm_asset.', 'easy'),
  mcq('ast-t03', 'In stock', 'install_status 6 on assets commonly means:', ['In use', 'In stock', 'Retired', 'Stolen'], 1, 'Confirm choices; 6 is often In stock, 1 In use, 7 Retired.', 'easy'),
  mcq('ast-t04', 'assigned_to', 'Setting assigned_to on an asset typically means:', ['The support group', 'The user the asset is issued to', 'The vendor contact only', 'The CAB manager'], 1, 'User assignment of the physical/logical asset.', 'easy'),
  mcq('ast-t05', 'asset_tag', 'asset_tag is used as:', ['The sys_id', 'A unique business identifier for the asset', 'The serial number always', 'The model category sys_id'], 1, 'Tags are operational IDs; serial_number is manufacturer serial.', 'easy'),
  mcq('ast-t06', 'Sync to CI', 'When assigned_to changes on an asset with a linked CI, a BR may:', ['Delete the CI', 'Copy assigned_to onto cmdb_ci', 'Publish knowledge', 'Open a change automatically always'], 1, 'Keep CI assignment aligned with the asset.', 'intermediate'),
  mcq('ast-t07', 'updateMultiple', 'GlideRecord.updateMultiple() is appropriate when:', ['You must run after BR on every row with different logic', 'You set field values then apply them to all queried rows at once', 'You are in a client script', 'You need GlideAjax'], 1, 'Set values on the prototype then updateMultiple; engines may be limited.', 'intermediate'),
  mcq('ast-t08', 'Duplicate serials', 'Finding duplicate serial_number values uses:', ['g_form.addOption', 'GlideAggregate COUNT groupBy serial_number and count > 1', 'IRE only', 'A Scripted REST GET to /incident'], 1, 'Aggregate then inspect counts.', 'intermediate'),
  mcq('ast-t09', 'Stockroom', 'stockroom is required when in stock because:', ['In-stock assets should have a location/stockroom', 'Stockroom is a journal field', 'It replaces serial_number', 'ITIL forbids assigned_to'], 0, 'Inventory control.', 'easy'),
  mcq('ast-t10', 'Warranty query', 'warranty_expiration < javascript:gs.now() in an encoded query finds:', ['Assets under warranty', 'Assets whose warranty date is already past', 'Assets without a model', 'Only retired assets'], 1, 'Expired warranty filter.', 'intermediate'),
  mcq('ast-t11', 'Return to stock', 'Returning an asset to stock usually includes:', ['Deleting assigned_to user records', 'Clearing assigned_to and setting install_status to in stock', 'Setting major_incident_state', 'Calling RESTMessageV2'], 1, 'Unassign and restock.', 'easy'),
  mcq('ast-t12', 'Substatus', 'Retire substatus (for example disposed) exists to:', ['Replace install_status', 'Clarify why/how an asset left the operational inventory', 'Store the CI class', 'Hold the request number'], 1, 'Substatus qualifies the lifecycle state.', 'easy'),
  mcq('ast-t13', 'Incident CI to asset', 'Finding assets for an incident CI uses:', ['alm_asset.addQuery("ci", incident.cmdb_ci)', 'Always asset_tag = incident.number', 'problem_id', 'sc_cat_item'], 0, 'alm_asset.ci references the CI.', 'intermediate'),
  mcq('ast-t14', 'Prevent delete in use', 'Blocking delete when install_status is In use protects:', ['The MID Server', 'Inventory/audit integrity while the asset is deployed', 'The knowledge base', 'GlideAjax'], 1, 'Return to stock or retire first.', 'easy'),
  mcq('ast-t15', 'Model grouping', 'GlideAggregate groupBy model on alm_asset answers:', ['Open incidents per model', 'How many assets exist per model', 'Change risk', 'SLA percentage'], 1, 'Fleet counts by model.', 'easy'),
];
