import { mcq } from './helpers.js';

export const theory = [
  mcq(
    'sla-t01',
    'Retroactive start',
    'SLA attaches 30 minutes after insert because priority was updated to P1. Retroactive start is true. What does the engine do, and what must exist?',
    [
      'It always starts from now; retroactive is a label only',
      'It backdates start using audit history of when the start condition became true; if the driving fields are not audited, the backdate is wrong or missing',
      'It deletes the first 30 minutes from the database',
      'It requires a MID Server',
    ],
    1,
    'Community/docs: retroactive start/pause/stop replay audit. CIS-ITSM loves this. Enable auditing on priority/state. Incomplete audit = SLA that “starts now” despite the checkbox.',
    'hard',
  ),
  mcq(
    'sla-t02',
    'Retroactive pause',
    'Incident went On Hold 2 hours ago but the SLA didn’t pause. You enable Retroactive Pause. Result?',
    [
      'Pause still starts from now only',
      'Engine looks back to when the pause condition first became true and excludes that wait from elapsed, if audit supports it',
      'It converts the SLA to cancelled',
      'It clones a second task_sla',
    ],
    1,
    'Same audit dependency. If On Hold is a substate that isn’t in the pause condition, retroactive cannot invent a pause.',
    'hard',
  ),
  mcq(
    'sla-t03',
    'Schedule vs 24x7',
    'P1 4-hour SLA uses 8–5 weekdays. A ticket opens Saturday 01:00. Elapsed after 1 wall-clock hour is ~0. Why do agents argue “we’re already late”?',
    [
      'The SLA is broken',
      'Elapsed follows GlideSchedule; time outside the schedule does not count (unless 24x7). Agents confuse wall clock with business time',
      'Schedules cannot be attached to SLAs',
      'P1 must ignore schedules OOTB with no property',
    ],
    1,
    'Display BR + g_scratchpad to warn “outside business hours” is a known pattern. Interview: define P1 as 24x7 if the contract says so.',
    'hard',
  ),
  mcq(
    'sla-t04',
    'Multiple SLAs on one task',
    'Response SLA and Resolution SLA both in_progress. Breach of response does not cancel resolution. Correct?',
    [
      'False; only one task_sla can exist per task',
      'True; multiple definitions can attach; they have independent clocks, stages, and breach flags',
      'The older SLA always wins and kills the other',
      'GlideAggregate cannot count them',
    ],
    1,
    'CIS: multiple SLAs. made_sla on the task is a rollup you must understand (any breach vs all). Don’t assume one row in task_sla.',
    'hard',
  ),
  mcq(
    'sla-t05',
    'Pause condition vs client hold_reason',
    'On Hold pauses SLA, but agents use a custom u_waiting_vendor state that is not in the pause condition. Symptom?',
    [
      'SLA still pauses because any non-In-Progress state pauses OOTB',
      'Clock keeps running; UI Policy cannot pause SLAs — pause is SLA definition conditions evaluated by the engine on update',
      'hold_reason mandatory pauses SLAs by itself',
      'You must call gs.sleep to pause',
    ],
    1,
    'Configure pause conditions for every waiting state. Client mandatory hold_reason is UX, not the clock.',
    'hard',
  ),
  mcq(
    'sla-t06',
    'Retroactive start vs SLA breakdown',
    'SLA Breakdown by assignment group attributes early time to the wrong assignee. Known interaction?',
    [
      'Breakdown ignores assignment',
      'With retroactive start, breakdown may only see assignee changes after the SLA record attached, attributing backdated time to the first assignee it sees',
      'This cannot happen if has_breached is false',
      'Breakdown requires SOAP',
    ],
    1,
    'ServiceNow community: retroactive start + SLA breakdown mismatch. Implementation choice: disable retroactive or custom breakdown.',
    'hard',
  ),
  mcq(
    'sla-t07',
    'getRowCount of task_sla in a BR',
    'Before BR on incident counts related SLAs with GlideRecord query + getRowCount on every update. Production issue?',
    [
      'None; it is O(1)',
      'Extra query on a hot table; use GlideAggregate, cache on g_scratchpad for display, or check only when state/priority changes (condition field)',
      'task_sla cannot be queried from incident BRs',
      'You must use RESTMessageV2 to localhost',
    ],
    1,
    'Incident is the hottest table. Condition + aggregate. Display BR if it is only for the form.',
    'hard',
  ),
  mcq(
    'sla-t08',
    'Reset vs repair',
    'Reopen Resolved → In Progress. Customer wants a fresh resolution SLA. What actually happens OOTB-ish?',
    [
      'Always a brand-new task_sla with no config',
      'Depends: existing SLA may resume/cancel/reset based on reset conditions and SLA definition; “repair” scripts exist because reopen is an edge case CIS tests',
      'Reopen always deletes CMDB relationships',
      'You cannot reopen incidents that had SLAs',
    ],
    1,
    'Don’t promise a new 4-hour clock unless reset conditions are built. Test it on a PDI.',
    'hard',
  ),
  mcq(
    'sla-t09',
    'contract_sla vs sla table names',
    'You GlideRecord("sla") in a Tokyo+ instance and get nothing. Why might that be?',
    [
      'SLAs were removed from ITSM',
      'Definition table is typically contract_sla (or the family-specific SLA definition); “sla” as a table name is a common wrong guess',
      'You must query ecc_queue',
      'Definitions live only in XML update sets, not tables',
    ],
    1,
    'Runtime = task_sla. Definition = contract_sla in many ITSM apps. Verify sys_db_object on the target family.',
    'hard',
  ),
  mcq(
    'sla-t10',
    'Percentage workflow',
    'Why do SLA workflows use 50%/75% instead of “2 hours” in the flow?',
    [
      'Percentages are less accurate',
      'One generic flow can serve 4-hour and 3-day SLAs; time-based waits would need a flow per duration',
      'The engine cannot read duration fields',
      'Percentages ignore schedules',
    ],
    1,
    'CIS-ITSM study notes: percentage-based SLA notifications. Elapsed still honors schedule.',
    'hard',
  ),
  mcq(
    'sla-t11',
    'made_sla true but has_breached true',
    'How is that possible?',
    [
      'It is impossible in all versions',
      'made_sla may be calculated at close from a subset of SLAs, a BR that doesn’t see all task_sla rows, or a customized field — don’t treat the two as a DB constraint',
      'has_breached is client-only',
      'made_sla is on contract_sla only',
    ],
    1,
    'Interview: query all task_sla for the task. Don’t trust one boolean.',
    'hard',
  ),
  mcq(
    'sla-t12',
    'Stopping SLAs on cancel',
    'Setting stage=cancelled with setWorkflow(false) on task_sla. Side effect?',
    [
      'The SLA engine will still send breach emails forever',
      'You may skip SLA engine’s own stop processing/notifications; sometimes that’s desired for cancel storms, but reporting of “cancelled vs breached” can be wrong if you just flip the choice',
      'cancelled is not a valid stage name in any family',
      'You must delete the row instead, always',
    ],
    1,
    'Prefer letting the stop condition fire (incident cancelled) over hand-editing task_sla. If you must, know you are mutating runtime.',
    'hard',
  ),
  mcq(
    'sla-t13',
    'OLA vs SLA vs UC',
    'Assignment group internal 15-min acknowledge vs customer 4-hour resolve. Modeling?',
    [
      'One SLA definition can be both',
      'Separate definitions (SLA to customer, OLA to internal team); don’t overload a single contract_sla with mixed audiences',
      'OLAs cannot be task_sla',
      'UCs replace CMDB',
    ],
    1,
    'CIS vocabulary. Different start/pause/notify. Same task can have both.',
    'hard',
  ),
  mcq(
    'sla-t14',
    'GlideSchedule.isInSchedule',
    'Checking “are we in the SLA schedule now” in a Display BR. Why Display not After?',
    [
      'After BRs run on form load',
      'You need the answer when the form opens, passed via g_scratchpad; After does not run on GET of the form',
      'Display BRs cannot query task_sla',
      'GlideSchedule is client-only',
    ],
    1,
    'Pattern from community: Display BR + onLoad info message for outside hours. Keep the query tight (current task’s in_progress SLAs only).',
    'hard',
  ),
  mcq(
    'sla-t15',
    'Priority change and multiple definitions',
    'P3 SLA in_progress; user sets P1. What should happen in a well-built instance?',
    [
      'The P3 SLA always continues as the only clock',
      'P3 stop condition should cancel/complete it and P1 definition should attach (possibly retroactive) — if stop conditions are wrong you get two running SLAs or a P3 clock on a P1 ticket',
      'Priority cannot be changed after insert',
      'All task_sla rows are deleted on any update',
    ],
    1,
    'CIS edge case. Test stop conditions include priority change. Retroactive on the P1 SLA is a business decision.',
    'hard',
  ),
];
